[otfc]
host=localhost
port=15432
dbname=otfc
user=solved_readonly_user

[hlb]
host=localhost
port=15432
dbname=hlb
user=solved_readonly_user

[penp]
host=localhost
port=15432
dbname=penp
user=solved_readonly_user

[rsa]
host=localhost
port=15432
dbname=rsa
user=solved_readonly_user

[bvh]
host=localhost
port=15432
dbname=bvh
user=solved_readonly_user

[care247]
host=localhost
port=15432
dbname=c247
user=solved_readonly_user

[console]
host=localhost
port=15432
dbname=c247
user=solved_readonly_user
